sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
env:
  global:
  - PATH=$PATH:$HOME/google-cloud-sdk/bin
  - PROJECT_ID="kubernetes"
  - ZONE="us-central1-a"
  - IMAGE_NAME=demo:latest
  - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
  - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/kubernetes-f5afd7908cf3.json"
  - CLUSTER_NAME=travis-demo
before_install:
- openssl aes-256-cbk -K $encrypted_142535234c_key -iv $encrypted_12323423423440c_in -in kubernetes-f5afd7908cf3.json.enc -out kubernetes-f5afd7908cf3.json -d 
- ./gcloud-sdk-install.sh
- source /home/travis/.bashrc
- ./gcloud-sdk-configure.sh
install: true
before_script:
- ./image-prepare.sh $FULL_IMAGE_NAME
- ./image-push.sh $FULL_IMAGE_NAME
script:
- ./gcloud-select-cluster.sh $CLUSTER_NAME
- ./k8s-run-mysql.sh ''